"""
Screened ticker universe for the exhaustion dashboard.

Rebuild with: .venv/Scripts/python.exe -m webapp.build_universe
Base criteria: price $5-$50, above SMA200, SMA50 > SMA200, weekly
volatility > 5% -- matches the screen used to curate p.py's
target_universe. Cap/volume floor is tunable (see --min-cap/--min-vol).
"""

TICKERS = [
    'AAL', 'AAP', 'ABCL', 'ABEO', 'ABSI', 'ABX', 'ACHC', 'ACHV',
    'ACMR', 'ACRS', 'ADEA', 'ADPT', 'ADTN', 'AEHR', 'AESI', 'AEVA',
    'AFRM', 'AGIO', 'AHCO', 'AIP', 'ALGM', 'ALKS', 'ALMS', 'ALTO',
    'AMBQ', 'AMCX', 'AMKR', 'AMLX', 'AMN', 'AMRX', 'ANAB', 'ANNX',
    'AOSL', 'APA', 'APPS', 'ARKO', 'ARTV', 'ARWR', 'ARX', 'ASC',
    'ASPN', 'ASTH', 'ASX', 'ATAI', 'ATRO', 'AUR', 'AURA', 'AVBP',
    'AVNS', 'AVNT', 'AVR', 'AVTX', 'AXGN', 'AXTI', 'BAND', 'BAX',
    'BB', 'BBAR', 'BBIO', 'BBY', 'BC', 'BCAX', 'BCRX', 'BEAM',
    'BFH', 'BFLY', 'BHE', 'BHVN', 'BIOA', 'BIRK', 'BKD', 'BKR',
    'BLFS', 'BLMN', 'BLZE', 'BRKR', 'BROS', 'BRUN', 'BVS', 'BZH',
    'CADL', 'CALY', 'CART', 'CBRL', 'CCRN', 'CDNA', 'CECO', 'CEVA',
    'CGEM', 'CGNT', 'CGNX', 'CGON', 'CLDX', 'CLMT', 'CLYM', 'CMBT',
    'CMP', 'CMPS', 'CNC', 'CNK', 'COCO', 'CODI', 'COGT', 'COHU',
    'COLD', 'COLM', 'COMP', 'CORT', 'CORZ', 'CRI', 'CRNX', 'CRSR',
    'CRVS', 'CSTM', 'CTOS', 'CVI', 'CYRX', 'CYTK', 'CZR', 'DAL',
    'DAR', 'DBRG', 'DFTX', 'DINO', 'DIOD', 'DK', 'DMRA', 'DNLI',
    'DNTH', 'DRS', 'DRTS', 'DSGN', 'DT', 'DXCM', 'DYN', 'EFXT',
    'EGY', 'ELAN', 'ELVA', 'ELVN', 'EMN', 'ENPH', 'EPC', 'EQNR',
    'ERAS', 'ESI', 'ESTA', 'ETOR', 'ETSY', 'EVC', 'EVER', 'EVH',
    'EWTX', 'EXTR', 'F', 'FA', 'FCEL', 'FCX', 'FDMT', 'FIVN',
    'FLR', 'FLYW', 'FNKO', 'FRO', 'FROG', 'FSLY', 'FTDR', 'FTRE',
    'FUN', 'GBTG', 'GEN', 'GEO', 'GFS', 'GGAL', 'GLNG', 'GLUE',
    'GPRE', 'GPRK', 'GRND', 'GRPN', 'GSAT', 'GTES', 'GTX', 'HAE',
    'HAL', 'HAPN', 'HCSG', 'HELE', 'HGV', 'HIMX', 'HLIT', 'HLX',
    'HNGE', 'HP', 'HPE', 'HPK', 'HPP', 'HPQ', 'HRMY', 'HTLD',
    'HUBG', 'HUN', 'HUT', 'IART', 'IBRX', 'ICHR', 'IFF', 'ILPT',
    'IMAX', 'IMMX', 'IMNM', 'IMVT', 'INDV', 'INGM', 'INTC', 'IRDM',
    'ITGR', 'JBIO', 'JBLU', 'JEF', 'JHX', 'KGS', 'KLIC', 'KMT',
    'KMX', 'KNF', 'KNSA', 'KNTK', 'KOD', 'KTB', 'KURA', 'KYIV',
    'LASR', 'LEVI', 'LFST', 'LGN', 'LILA', 'LILAK', 'LINC', 'LIND',
    'LION', 'LIVN', 'LPG', 'LQDA', 'LTH', 'LTM', 'LUV', 'LYB',
    'LZB', 'M', 'MAMA', 'MAN', 'MBX', 'MCHP', 'MD', 'MEI',
    'MEOH', 'MGA', 'MGNI', 'MGTX', 'MITK', 'MLTX', 'MRAM', 'MRCY',
    'MRNA', 'MRVI', 'MRX', 'MT', 'MTDR', 'MTH', 'MUR', 'MXL',
    'NAT', 'NE', 'NEO', 'NEOG', 'NESR', 'NEXA', 'NEXT', 'NKTR',
    'NOK', 'NOV', 'NRIX', 'NSA', 'NSP', 'NVCR', 'NVRI', 'NVST',
    'NWL', 'OBE', 'OEC', 'OGN', 'OMCL', 'OMDA', 'ON', 'OPLN',
    'OPTX', 'ORKA', 'OSCR', 'OSS', 'OUST', 'PACK', 'PACS', 'PANL',
    'PARR', 'PAYO', 'PAYS', 'PBF', 'PBI', 'PCRX', 'PCVX', 'PDFS',
    'PENG', 'PENN', 'PGNY', 'PII', 'POWI', 'PRAA', 'PRCH', 'PRG',
    'PRKS', 'PRM', 'PRMB', 'PSNL', 'PTCT', 'PTEN', 'PUBM', 'PUMP',
    'PVH', 'QMCO', 'QNST', 'QURE', 'RAL', 'RAMP', 'RBRK', 'RCUS',
    'RELY', 'REPL', 'RHI', 'RIOT', 'RLAY', 'RLMD', 'RNG', 'RSI',
    'RXO', 'RYAM', 'S', 'SEDG', 'SEI', 'SGHC', 'SGMT', 'SHLS',
    'SHOO', 'SKM', 'SKYT', 'SLB', 'SLDB', 'SLDE', 'SLG', 'SLS',
    'SM', 'SNDR', 'SNDX', 'SRRK', 'SRTA', 'SSL', 'STAA', 'STGW',
    'STM', 'STNG', 'STTK', 'SVCO', 'SVRA', 'SW', 'SWBI', 'SWK',
    'SXC', 'SYRE', 'TALK', 'TALO', 'TBLA', 'TDAY', 'TDC', 'TDOC',
    'TDW', 'TECK', 'TENB', 'TENX', 'TEO', 'TEVA', 'TEX', 'TGB',
    'TGTX', 'TH', 'TIGO', 'TILE', 'TK', 'TNGX', 'TOI', 'TPC',
    'TREX', 'TRLV', 'TRMD', 'TRN', 'TRVI', 'TSHA', 'TVTX', 'TWO',
    'TWST', 'TXG', 'TYRA', 'UA', 'UAA', 'UCTT', 'ULCC', 'ULS',
    'UMAC', 'UMC', 'UNFI', 'UNIT', 'URBN', 'URGN', 'UTI', 'VAL',
    'VCEL', 'VCYT', 'VECO', 'VG', 'VIAV', 'VIR', 'VIRT', 'VIST',
    'VRNS', 'VSAT', 'VSH', 'VSTS', 'VSXY', 'VVX', 'WBD', 'WERN',
    'WEST', 'WHD', 'WNC', 'WRBY', 'WSC', 'WT', 'WTTR', 'WULF',
    'WYFI', 'XENE', 'XMAX', 'XMTR', 'XPRO', 'XYZ', 'YETI', 'YOU',
    'YPF', 'ZD', 'ZETA', 'ZGN', 'ZIM', 'ZM', 'ZVRA', 'ZYME',
]
