"""
Screened ticker universe for the exhaustion dashboard.

Rebuild with: .venv/Scripts/python.exe -m webapp.build_universe
Base criteria: price $5-$50, above SMA200, SMA50 > SMA200, weekly
volatility > 5% -- matches the screen used to curate p.py's
target_universe. Cap/volume floor is tunable (see --min-cap/--min-vol).
"""

TICKERS = [
    'AAL', 'ABCL', 'ABEO', 'ABSI', 'ABX', 'ACDC', 'ACHC', 'ACHV',
    'ACRS', 'ADEA', 'ADPT', 'ADTN', 'ADUR', 'AESI', 'AEVA', 'AGIO',
    'AGRO', 'AIP', 'ALM', 'ALMS', 'ALOY', 'ALTO', 'AMCX', 'AMLX',
    'AMN', 'AMPG', 'AMRX', 'ANGO', 'ANNX', 'ANRO', 'AOSL', 'APA',
    'APPS', 'ARKO', 'ARTV', 'ASC', 'ASPN', 'ASTH', 'ASX', 'ASYS',
    'ATAI', 'ATOM', 'AUR', 'AURA', 'AVBP', 'AVNS', 'AVNT', 'AVR',
    'AVTX', 'AXGN', 'AYA', 'BAX', 'BB', 'BBAR', 'BBCP', 'BCAX',
    'BCRX', 'BEAM', 'BFLY', 'BHVN', 'BIOA', 'BIRK', 'BKD', 'BLFS',
    'BLMN', 'BLZE', 'BNED', 'BRUN', 'BVS', 'BW', 'BWEN', 'BWLP',
    'BZH', 'CADL', 'CALY', 'CART', 'CBIO', 'CBLL', 'CC', 'CCRN',
    'CDNA', 'CEPU', 'CEVA', 'CGAU', 'CGEM', 'CGNT', 'CHRN', 'CIFR',
    'CLDX', 'CLMT', 'CLSK', 'CLYM', 'CMBT', 'CMP', 'CMPS', 'CNK',
    'CODI', 'COGT', 'COLD', 'CORZ', 'CPIX', 'CRI', 'CRNC', 'CRSR',
    'CRVS', 'CSTM', 'CTNM', 'CTOS', 'CUE', 'CVI', 'CXDO', 'CYRX',
    'CZR', 'DBRG', 'DCTH', 'DFTX', 'DIN', 'DLX', 'DMRA', 'DNLI',
    'DOW', 'DRS', 'DRTS', 'DSGN', 'DTIL', 'DYN', 'EFXT', 'EGY',
    'ELAN', 'ENPH', 'EOLS', 'EPC', 'EQNR', 'ERAS', 'ESI', 'ETON',
    'ETOR', 'EVC', 'EVH', 'EWTX', 'EXTR', 'F', 'FA', 'FCEL',
    'FDMT', 'FIRY', 'FIVN', 'FLYW', 'FNKO', 'FRO', 'FSLY', 'FTRE',
    'FUN', 'GBTG', 'GCMG', 'GDOT', 'GEN', 'GEO', 'GLAS', 'GLUE',
    'GPRE', 'GPRK', 'GRDN', 'GRND', 'GRPN', 'GRRR', 'GTE', 'GTES',
    'GTX', 'HAL', 'HAPN', 'HBM', 'HCSG', 'HELE', 'HGV', 'HIMX',
    'HLIT', 'HLX', 'HP', 'HPE', 'HPK', 'HPP', 'HPQ', 'HRMY',
    'HSHP', 'HTLD', 'HUBG', 'HUN', 'HZO', 'IART', 'IBRX', 'ILPT',
    'IMAX', 'IMMR', 'IMMX', 'IMNM', 'IMVT', 'INDV', 'INNV', 'INTT',
    'INVX', 'IRDM', 'ISSC', 'JBIO', 'JBLU', 'JHX', 'KELYA', 'KMT',
    'KOD', 'KPTI', 'KRO', 'KURA', 'KYIV', 'LAR', 'LBRT', 'LEGN',
    'LEVI', 'LFST', 'LILA', 'LILAK', 'LIND', 'LION', 'LOMA', 'LPG',
    'LPTH', 'LTH', 'LUV', 'LXU', 'LYTS', 'LZB', 'M', 'MAMA',
    'MAN', 'MD', 'MEC', 'MEI', 'MGNI', 'MGTX', 'MITK', 'MLTX',
    'MRAM', 'MRVI', 'MTUS', 'MUR', 'NAT', 'NE', 'NEO', 'NEOG',
    'NESR', 'NEXA', 'NEXN', 'NEXT', 'NOK', 'NOV', 'NRIX', 'NSA',
    'NSP', 'NVCR', 'NVRI', 'NVST', 'NVTS', 'NWL', 'NX', 'OBE',
    'OCC', 'OGN', 'OMCL', 'OMDA', 'OPLN', 'OPRA', 'OPRT', 'OPTX',
    'ORN', 'OSCR', 'OSPN', 'OSS', 'OUST', 'PACK', 'PACS', 'PANL',
    'PAYO', 'PAYS', 'PBI', 'PCRX', 'PENN', 'PGEN', 'PGNY', 'PHVS',
    'PL', 'PLSE', 'POET', 'PRAA', 'PRCH', 'PRG', 'PRKS', 'PRM',
    'PRMB', 'PRTH', 'PSNL', 'PTEN', 'PUBM', 'PUMP', 'QMCO', 'QTTB',
    'QUIK', 'QURE', 'RAMP', 'RAPP', 'RCUS', 'RELY', 'REPL', 'REPX',
    'RFIL', 'RHI', 'RIG', 'RILY', 'RIOT', 'RLAY', 'RLMD', 'RMAX',
    'RNG', 'RRGB', 'RSI', 'RXO', 'RYZ', 'S', 'SCHL', 'SEPN',
    'SG', 'SGHC', 'SGMT', 'SHLS', 'SHOO', 'SION', 'SKE', 'SKM',
    'SKYT', 'SLB', 'SLDB', 'SLDE', 'SLG', 'SLN', 'SLP', 'SLS',
    'SM', 'SND', 'SNDR', 'SNDX', 'SPIR', 'SRTA', 'SSL', 'SSRM',
    'STAA', 'STGW', 'STRO', 'STTK', 'SVCO', 'SVRA', 'SW', 'SWBI',
    'SXC', 'TALK', 'TALO', 'TBI', 'TBLA', 'TBRG', 'TCMD', 'TDAY',
    'TDC', 'TDOC', 'TE', 'TENB', 'TENX', 'TEO', 'TEVA', 'TGB',
    'TGS', 'TH', 'TILE', 'TK', 'TNGX', 'TOI', 'TORO', 'TREX',
    'TRLV', 'TRMD', 'TRN', 'TRT', 'TRVI', 'TSHA', 'TTI', 'TWO',
    'TXG', 'TYRA', 'UA', 'UAA', 'ULCC', 'UMAC', 'UMC', 'UNFI',
    'UNIT', 'URGN', 'UTI', 'VCEL', 'VELO', 'VG', 'VIAV', 'VIR',
    'VRNS', 'VSH', 'VSTS', 'WBD', 'WERN', 'WEST', 'WNC', 'WRBY',
    'WSC', 'WT', 'WTTR', 'WULF', 'WYFI', 'WYY', 'XMAX', 'XPER',
    'XPRO', 'YETI', 'YPF', 'ZETA', 'ZGN', 'ZIM', 'ZVRA', 'ZYME',
]
